### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Hujan",
    "email": "aku@mail.com",
    "password": "rahasia"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "aku@mail.com",
    "password": "rahasia"
}

### Get user profile
GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzgyNjYsImlkIjoxNH0.YtRn-sAJbMgLayrqLC9W0e1meK35RqnvjMywn-LqoYo

### Update user profile
PATCH  http://localhost:3000/api/auth/profile
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzgyNjYsImlkIjoxNH0.YtRn-sAJbMgLayrqLC9W0e1meK35RqnvjMywn-LqoYo

{
    "name": "Dicki profile",
    "password": "password"
}

### Get user by id
GET  http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzgyNjYsImlkIjoxNH0.YtRn-sAJbMgLayrqLC9W0e1meK35RqnvjMywn-LqoYo

### Get all user
GET  http://localhost:3000/api/users?page=1&page_size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzgyNjYsImlkIjoxNH0.YtRn-sAJbMgLayrqLC9W0e1meK35RqnvjMywn-LqoYo