services:
  go-clean-architecture:
    container_name: fiber-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    volumes:
      - fiber-app:/app
    networks:
      - application
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    container_name: postgres-db
    image: postgres:alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - application

volumes:
  fiber-app:
  postgres-db:

networks:
  application:
    driver: bridge