services:
  go-clean-architecture:
    container_name: fiber-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:${APP_PORT}
    volumes:
      - fiber-app:/app
    networks:
      - application
    depends_on:
      - postgres
    command: ./fiber

  postgres:
    container_name: postgres-db
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application

volumes:
  fiber-app:
  postgres-db:

networks:
  application:
