basePath: /
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Go Clean Architecture With Fiber Framework
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Clean Architecture With Fiber
  version: 1.0.0
paths: {}
swagger: "2.0"
